/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-03-09 06:35:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _12_005f01_005fvalidation02_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Validation</title>\r\n");
      out.write("<style>\r\n");
      out.write("form {\r\n");
      out.write("	width: 60%;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<form name=\"frm\" action=\"12_01_validation_process.jsp\" method=\"post\">\r\n");
      out.write("		<fieldset>\r\n");
      out.write("			<legend>exec()메소드 사용: </legend>\r\n");
      out.write("			<label for=\"itt\">제목 : </label> \r\n");
      out.write("			<input type=\"text\" name=\"itt\" id=\"itt\" value=\"java server Pages\" required><br> \r\n");
      out.write("			<input type=\"button\" value=\"전송\" onclick=\"checkForm()\">\r\n");
      out.write("\r\n");
      out.write("		</fieldset>\r\n");
      out.write("\r\n");
      out.write("	</form>\r\n");
      out.write("	<script>\r\n");
      out.write("		/* 유효성 검사 : 데이터가 전송되기 전 폼 입력값이 규칙에 맞게 입력되었는지 확인하는 것\r\n");
      out.write("		 정규 표현식 :특정한 규칙을 가진 문자열의 집합을 표현하는데 사용하는 형식 언어\r\n");
      out.write("		 형식:\r\n");
      out.write("			 1.var 변수명 = /정규표현식/[flag];\r\n");
      out.write("		2.var 변수명 = new RegExp('정규표현식',['Flag']);\r\n");
      out.write("		flag값 :\r\n");
      out.write("		 i - 대소문자 구분 없이 검사\r\n");
      out.write("		 g - 문자열 내의 모든 패턴을 검사\r\n");
      out.write("		 m -문자열에 줄바꿈형이 있는지 검사\r\n");
      out.write("		 \r\n");
      out.write("		 문자열 판단 메소드\r\n");
      out.write("		 test() : 매개 변수 값으로 전달되는 문자열이 정규표현식에 부합한 지 판단하여 boolean판단\r\n");
      out.write("		 exec() : 매개 변수 값으로 전달되는 문자열에서 정규 표현식에 문자열을 추출하여 반환함.\r\n");
      out.write("		 \r\n");
      out.write("		 \r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		 */\r\n");
      out.write("		function checkForm() {\r\n");
      out.write("			var regExp = /Java server/i;\r\n");
      out.write("			//Java server문자열이 포함되었는지 여부 판단,문자 그대로 입력해야함. i :대소문자 구분없이\r\n");
      out.write("			//var regExp = new RegExp('Java server','i');\r\n");
      out.write("			var str = document.frm.itt.value;\r\n");
      out.write("			//var result = regExp.exex(str);\r\n");
      out.write("			var result = regExp.test(str);\r\n");
      out.write("			alert(result);\r\n");
      out.write("			if (result == false)\r\n");
      out.write("				return false;\r\n");
      out.write("			else\r\n");
      out.write("				document.frm.submit();\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
